### ISSUE TITLE
how to usel TrialRemoveal for dll?

### ISSUE THREAD

**Issue by Charltsing** [CodeVirtualZ/EazfuscatorTrialRemoveal#1]
how to usel TrialRemoveal for dll ?

**Comment by CodeVirtualZ** [comment]
In **private void Button_Click** 
you can change **openFileDialog.Filter** for allow .dll files like that
![image](https://github.com/CodeVirtualZ/EazfuscatorTrialRemoveal/assets/64941708/db43b59b-3e3e-41d7-bc13-cb61bcef5298)
